import { tokens } from './tokens.js';

// Source: design_handoff_v5/design/shared.jsx (GROUPS).
// Featured groups data used by the SocialRail / FeaturedGroups carousel.
export const GROUPS = [
  { name: 'Zebras Unite Global',
    purpose: 'An international, intersectional movement that promotes a more ethical and inclusive startup culture.',
    members: '925', loc: 'Distributed · Global', tag: 'Inclusive Capital',
    color: tokens.proposalPurple, bg: tokens.proposalPurpleSoft, avatar: '#6B5AB7',
    avatarImg: '/v5/groups/zebras-unite-global-avatar.png',
    coverImg: '/v5/groups/zebras-unite-global-cover.jpg',
    url: 'https://www.hylo.com/groups/zebras-unite' },
  { name: 'otherWise',
    purpose: 'A learning commons and gathering ground to reconnect people and their homeplaces.',
    members: '154', loc: 'Cosmolocal · Vermont', tag: 'Community of Care',
    color: tokens.requestTeal, bg: tokens.requestTealSoft, avatar: '#0DB89C',
    avatarImg: '/v5/groups/otherwise-avatar.png',
    coverImg: '/v5/groups/otherwise-cover.png',
    url: 'https://www.hylo.com/groups/otherwise' },
  { name: 'Klamath Watershed Weavers',
    purpose: 'Bioregional coordination across the Klamath basin — from headwaters to coast.',
    members: '432', loc: 'Klamath Basin, OR/CA', tag: 'Bioregional',
    color: '#2E8B57', bg: '#D9EEDE', avatar: '#3C7D4A',
    avatarImg: '/v5/groups/klamath-watershed-weavers-avatar.jpg',
    coverImg: '/v5/groups/klamath-watershed-weavers-cover.jpg',
    url: '' },
  { name: 'The Stewardship School',
    purpose: 'A learning community for emerging community organizers and facilitators.',
    members: '2,104', loc: 'Online · cohort-based', tag: 'Learning',
    color: tokens.discussBlue, bg: tokens.discussBlueSoft, avatar: '#2F8EC4',
    avatarImg: '/v5/groups/stewardship-school-avatar.jpg',
    coverImg: '/v5/groups/stewardship-school-cover.jpg',
    url: '' },
  { name: 'Oakland Food Not Bombs',
    purpose: 'Twice-weekly community meals, produce share, and free store in downtown Oakland.',
    members: '318', loc: 'Oakland, CA', tag: 'Food Systems',
    color: tokens.projectOrange, bg: tokens.projectOrangeSoft, avatar: '#D96B1F',
    avatarImg: '/v5/groups/oakland-food-not-bombs-avatar.jpg',
    coverImg: '/v5/groups/oakland-food-not-bombs-cover.jpg',
    url: '' },
];
