import { tokens } from './tokens.js';

// Source: design_handoff_v5/design/shared.jsx (GROUPS).
// Featured groups data used by the SocialRail / FeaturedGroups carousel.
export const GROUPS = [
  { name: 'Common Good Missoula',
    purpose: 'Civic infrastructure for Missoula, Montana — participatory budgeting and community assemblies.',
    members: '1,240', loc: 'Missoula, MT', tag: 'Civic',
    color: tokens.proposalPurple, bg: tokens.proposalPurpleSoft, avatar: '#6B5AB7' },
  { name: 'Float',
    purpose: 'A nationwide mutual aid commons coordinating rent support and emergency care.',
    members: '8,612', loc: 'Distributed · US', tag: 'Mutual Aid',
    color: tokens.requestTeal, bg: tokens.requestTealSoft, avatar: '#0DB89C' },
  { name: 'Klamath Watershed Weavers',
    purpose: 'Bioregional coordination across the Klamath basin — from headwaters to coast.',
    members: '432', loc: 'Klamath Basin, OR/CA', tag: 'Bioregional',
    color: '#2E8B57', bg: '#D9EEDE', avatar: '#3C7D4A' },
  { name: 'The Stewardship School',
    purpose: 'A learning community for emerging community organizers and facilitators.',
    members: '2,104', loc: 'Online · cohort-based', tag: 'Learning',
    color: tokens.discussBlue, bg: tokens.discussBlueSoft, avatar: '#2F8EC4' },
  { name: 'Oakland Food Not Bombs',
    purpose: 'Twice-weekly community meals, produce share, and free store in downtown Oakland.',
    members: '318', loc: 'Oakland, CA', tag: 'Food Systems',
    color: tokens.projectOrange, bg: tokens.projectOrangeSoft, avatar: '#D96B1F' },
  { name: 'Bay Area Tool Library Network',
    purpose: 'Seven tool libraries sharing inventory, know-how and repair clinics.',
    members: '894', loc: 'SF Bay Area', tag: 'Commons',
    color: tokens.forest, bg: tokens.forestLight, avatar: '#2D7048' },
  { name: 'Cascadia Climate Collective',
    purpose: 'Regional climate action across Washington, Oregon and British Columbia.',
    members: '3,420', loc: 'Cascadia', tag: 'Climate',
    color: '#167F5A', bg: '#D6ECDE', avatar: '#1C8260' },
  { name: 'Pine Ridge Neighbors',
    purpose: 'Our block — events, requests, lost dogs, the occasional potluck.',
    members: '87', loc: 'Pine Ridge, Austin', tag: 'Neighborhood',
    color: tokens.rhino, bg: '#E1E6EE', avatar: '#4A5F78' },
  { name: 'Afrofuturist Ecologies',
    purpose: 'Black-led ecological stewardship, land return and speculative design.',
    members: '512', loc: 'Distributed', tag: 'Learning',
    color: tokens.proposalPurple, bg: tokens.proposalPurpleSoft, avatar: '#5B3E8A' },
  { name: 'Ridgewood Co-op',
    purpose: 'A worker-owned food co-op in Queens — 4,200 member-owners strong.',
    members: '4,212', loc: 'Queens, NY', tag: 'Co-op',
    color: tokens.projectOrange, bg: tokens.projectOrangeSoft, avatar: '#B85A1A' },
];
