import { tokens } from './tokens.js';

// Source: design_handoff_v5/design/shared.jsx (GROUPS).
// Featured groups data used by the SocialRail / FeaturedGroups carousel.
export const GROUPS = [
  { name: 'Zebras Unite Global',
    purpose: 'An international, intersectional movement that promotes a more ethical and inclusive startup culture.',
    members: '925', loc: 'Distributed · Global', tag: 'Inclusive Capital',
    color: tokens.proposalPurple, bg: tokens.proposalPurpleSoft, avatar: '#6B5AB7',
    avatarImg: '/v5/groups/zebras-unite-global-avatar.png',
    coverImg: '/v5/groups/zebras-unite-global-cover.jpg',
    url: 'https://www.hylo.com/groups/zebras-unite' },
  { name: 'Work That Reconnects Network',
    purpose: 'A global community of facilitators, collaborating in serivce to the Great Turning.',
    members: '8', loc: 'Distributed · Global', tag: 'Community of Practice',
    color: tokens.discussBlue, bg: tokens.discussBlueSoft, avatar: '#2F8EC4',
    avatarImg: '/v5/groups/wtrn-avatar.png',
    coverImg: '/v5/groups/wtrn-cover.png',
    url: 'https://www.hylo.com/groups/work-that-reconnects-network' },
{ name: 'Bay Delta Bioregion',
    purpose: 'A community advancing mutual support and local resilience in the Bay Delta bioregion.',
    members: '225', loc: 'Bay Area · California', tag: 'Bioregional',
    color: '#2E8B57', bg: '#D9EEDE', avatar: '#3C7D4A',
    avatarImg: '/v5/groups/bay-delta-bioregion-avatar.jpg',
    coverImg: '/v5/groups/bay-delta-bioregion-cover.jpg',
    url: 'https://www.hylo.com/groups/bay-area-bioregion' },
{ name: 'Planetary Health Alliance',
    purpose: 'Promoting action at the intersection of human health and the natural systems that sustain us.',
    members: '5280', loc: 'Distributed · Washington DC', tag: 'Public Health',
    color: tokens.projectOrange, bg: tokens.projectOrangeSoft, avatar: '#D96B1F',
    avatarImg: '/v5/groups/pha-avatar.png',
    coverImg: '/v5/groups/pha-cover.jpg',
    url: 'https://www.hylo.com/groups/pha' },
  { name: 'otherWise',
    purpose: 'A learning commons and gathering ground to reconnect people and their homeplaces.',
    members: '154', loc: 'Cosmolocal · Vermont', tag: 'Learning',
    color: tokens.requestTeal, bg: tokens.requestTealSoft, avatar: '#0DB89C',
    avatarImg: '/v5/groups/otherwise-avatar.png',
    coverImg: '/v5/groups/otherwise-cover.png',
    url: 'https://www.hylo.com/groups/otherwise' },
  { name: 'Bioregional Commons',
    purpose: 'Nurturing the global movement towards humans living in balance with our life-places.',
    members: '410', loc: 'Distributed · Global', tag: 'Bioregional',
    color: '#2E8B57', bg: '#D9EEDE', avatar: '#3C7D4A',
    avatarImg: '/v5/groups/bioregional-commons-logo.png',
    coverImg: '/v5/groups/bioregional-commons-cover.png',
    url: 'https://www.hylo.com/groups/bioregional-commons' },
];
