import { tokens } from '../tokens.js';

// Source: design_handoff_v5/design/v5-bring-your-group.jsx (PLATFORMS + PLATFORM_CONTENT).
// Section backgrounds alternate between cream/athens-gray and white per the design;
// `bg` is set as a hex on each platform to keep that scoped on a per-section basis.

export const PLATFORMS = [
  { id: 'facebook', name: 'Facebook Groups',           shortNav: null,             icon: 'fb',     bg: tokens.athensGray,
    oneLiner: 'The group platform everyone already has — and everyone knows the problems with.',
    works:  'Everyone is already there. The barrier to joining is zero. Facebook Groups have real reach — your posts can pull in new people, events get visibility, and notifications actually land. For casual community building, the network effect is hard to beat.',
    breaks: 'Your group’s attention is monetized. Facebook’s algorithm decides what members see, and it optimizes for engagement, not for what matters to your group. You can’t structure conversations, can’t run proposals or decisions, can’t connect with other groups, and can’t control your data. Members are constantly pulled away by ads and algorithmic distractions. You’re building on rented land — and the landlord is selling your community’s attention to advertisers.',
    hylo: [
      { t: 'No ads, no algorithm.',          d: 'Every member sees every post. You decide what’s important, not a feed algorithm.' },
      { t: 'Structured conversations.',      d: 'Discussions, events, requests, offers, projects, proposals — each with its own purpose, not all jammed into one feed.' },
      { t: 'Governance tools.',              d: 'Proposals, polls, roles, shared agreements. Your group can make decisions together, not just talk.' },
      { t: 'Cross-group coordination.',      d: 'Connect with other groups, share posts across networks, see the bigger picture. Facebook Groups are islands. Hylo groups are a network.' },
      { t: 'Your data stays yours.',         d: 'No tracking, no selling, no surveillance. Open source and community-governed.' },
    ],
    migration: 'Invite your members by email or shareable link. Most groups run both platforms in parallel for a few weeks while members transition. Your Facebook Group’s content can’t be exported automatically, but Hylo’s fresh start is often a feature, not a bug — it’s a chance to set clear agreements and build a healthier group culture from day one.',
  },
  { id: 'whatsapp', name: 'WhatsApp & Signal',         shortNav: null,             icon: 'chat',   bg: '#fff',
    oneLiner: 'Fast and intimate — until your group outgrows a chat thread.',
    works:  'Messaging apps are unbeatable for small, tight groups. Messages land instantly. Everyone has the app. For a handful of people coordinating something simple, nothing is faster. Signal adds real privacy.',
    breaks: 'Once a group passes about 20 active people, chat becomes overwhelming. Important messages get buried in minutes. There’s no way to organize conversations by topic, find a decision that was made last month, or onboard a new member without them drowning in scroll. Everything is ephemeral — nothing persists, nothing is findable, nothing builds on itself.',
    hylo: [
      { t: 'Chat when you want it, structure when you need it.', d: 'Hylo has real-time chat rooms alongside persistent, threaded discussions. Quick conversation and deep coordination live in the same place.' },
      { t: 'Everything is findable.',         d: 'Posts are tagged by topic, searchable, and organized by type. Three months from now, you can find the decision your group made about the garden project.' },
      { t: 'Subgroups without chaos.',        d: 'Create working groups, committees, or neighborhood pods — each with their own space, all connected to the parent group.' },
      { t: 'Requests and offers.',            d: 'Members can post what they need and what they can give. This is how mutual aid actually scales beyond “does anyone have a truck?”' },
      { t: 'A map.',                          d: 'See your members, events, and activity geographically. For place-based groups, this changes everything.' },
    ],
    migration: 'WhatsApp and Signal groups can’t be migrated, but that’s actually fine — the value of a chat app is the conversation, not the archive. Invite members to Hylo and let the chat group wind down naturally. Many groups keep a WhatsApp thread for quick/casual messages while using Hylo for everything that needs to persist, be found later, or involve more than simple chat.',
  },
  { id: 'slack', name: 'Slack & Discord',              shortNav: null,             icon: 'hash',   bg: tokens.athensGray,
    oneLiner: 'Built for companies and gaming communities. Adapted for everything else — awkwardly.',
    works:  'Slack and Discord are great at real-time team communication. Channels, threads, integrations, bots, search — for a company or a tight-knit team with a shared work context, they’re powerful. Discord’s voice channels and role systems add flexibility for more social communities.',
    breaks: 'Both platforms assume a single organizational context — one company, one server. They have no concept of groups connecting to other groups, no place-based logic, no governance or decision-making tools, and no mutual aid infrastructure. Slack hides your message history behind a paywall on the free tier. Neither is designed for groups that need to grow into self-governance.',
    hylo: [
      { t: 'Chat plus everything else.',      d: 'Topic-based chat rooms like Slack, but they exist alongside discussions, events, projects, proposals, and requests and offers. You don’t need a separate tool for each.' },
      { t: 'Cross-group coordination.',       d: 'Slack workspaces and Discord servers are walled off from each other. Hylo groups can connect, share posts, and coordinate across organizational boundaries.' },
      { t: 'No message paywall.',             d: 'Your full history is always available. Conversations, decisions, and context persist without a paid tier.' },
      { t: 'Built for communities, not companies.', d: 'Hylo’s role system, agreements, and governance tools are designed for shared stewardship — not top-down org charts.' },
      { t: 'Place-based organizing.',         d: 'Map view, geographic groups, watershed layers. If your work is rooted in a place, Hylo understands that. Slack and Discord don’t.' },
    ],
    migration: 'Slack and Discord histories can be exported. Many groups transition channel by channel, starting with the channels that need more structure — events, decisions, projects — while keeping Slack/Discord for pure chat until members are settled. Hylo’s chat rooms will feel familiar; the rest will feel like an upgrade.',
  },
  { id: 'mighty', name: 'Mighty Networks',             shortNav: null,             icon: 'ring',   bg: '#fff',
    oneLiner: 'The closest thing to Hylo in the commercial space — but built for a fundamentally different purpose.',
    works:  'Mighty Networks is a real community platform, not an adapted chat tool. It has groups, courses, events, member directories, and native mobile apps. If you’re a creator building a paid community around your content, Mighty is well-designed for that.',
    breaks: 'Mighty is built for creators monetizing audiences, not for communities coordinating together. Every network is a silo — your group can’t connect to, share with, or coordinate alongside other groups. No mutual aid infrastructure, no governance tools, no map or place-based logic. Pricing scales steeply, with transaction fees on every plan. And the platform is proprietary — if you leave, you leave with nothing.',
    hylo: [
      { t: 'Groups that connect.',            d: 'A mutual aid group can coordinate with a food co-op can coordinate with a neighborhood association — all visible to each other without merging.' },
      { t: 'Mutual support tools.',           d: 'Requests and offers, completion tracking, and AI-assisted matching. This is how trust gets built through action, not just conversation.' },
      { t: 'Governance and decisions.',       d: 'Proposals, polls, roles, agreements, and participatory funding rounds. Hylo is built for groups that want to make decisions together.' },
      { t: 'Place-based organizing.',         d: 'Map views, geographic groups, watershed layers. If your community is rooted in a place, Hylo was designed for you.' },
      { t: 'Open source, no lock-in.',        d: 'Hylo’s code is public. Your data is portable. There’s no exit penalty because the platform is built as a commons, not a business extracting from your community.' },
      { t: 'Free to start, fair to grow.',    d: 'Hylo’s core platform is free. Paid features exist for groups that need them, with no per-transaction fees on your community’s exchanges.' },
    ],
    migration: 'Mighty Networks allows you to export member email lists from your network settings. Invite members to Hylo, rebuild your group structure (about 15 minutes), and re-upload any key resources. The biggest gain: your group stops being an island and becomes part of a living network.',
  },
  { id: 'circle', name: 'Circle',                       shortNav: null,             icon: 'circle', bg: tokens.athensGray,
    oneLiner: 'A polished all-in-one for creators and course builders. Less suited for communities that aren’t centered on a single brand.',
    works:  'Circle is well-built and full-featured: spaces, courses, events, live streaming, automations, payments, custom branding, and a native mobile app. If you’re a solo creator or small business building a branded membership community, Circle is one of the best options on the market.',
    breaks: 'Circle is built for creators monetizing an audience — one brand, one community, one revenue stream. Each community is a silo with no ability to connect to other communities. No mutual aid, no governance, no decision-making tools, and no commons orientation. Pricing starts at $89/month and climbs, with transaction fees on every plan. The platform is closed-source.',
    hylo: [
      { t: 'Multi-group coordination.',       d: 'Hylo groups can nest, peer, and coordinate — essential for coalitions, networks, and place-based organizing where multiple groups need to work together.' },
      { t: 'Community governance.',           d: 'Proposals, agreements, roles, collective moderation, participatory budgeting. Hylo is for groups learning to govern themselves, not audiences organized around a creator.' },
      { t: 'Requests and offers.',            d: 'Built-in mutual support tools that build trust through reciprocal exchange. Circle has no equivalent.' },
      { t: 'Place and map.',                  d: 'Geographic groups, map views, watershed layers. For any community rooted in a physical place, this is a structural difference.' },
      { t: 'Commons, not commerce.',          d: 'Open source, non-profit, community-governed. No transaction fees on community exchanges. If Hylo ever stops serving your community, you can fork the code and leave.' },
      { t: 'Free core platform.',             d: 'Circle starts at $89/month. Hylo’s core is free — because we believe coordination infrastructure shouldn’t be paywalled.' },
    ],
    migration: 'Circle allows member CSV exports. Invite your community by email, set up your Hylo group (free, about 15 minutes), and migrate key content. The transition is straightforward for members — Hylo’s interface will feel familiar but the added depth of governance and cross-group tools will quickly become apparent.',
  },
  { id: 'notion', name: 'Notion & Google Workspace',   shortNav: 'Notion & Docs',  icon: 'doc',    bg: '#fff',
    oneLiner: 'Excellent for documents. Not a living community.',
    works:  'Notion is beautiful for documentation, project planning, and knowledge management. Google Workspace is the default for shared docs and spreadsheets. For internal team coordination where everyone already has context, these tools are powerful.',
    breaks: 'Documents are not relationships. Notion and Google Docs have no social layer — no member profiles, no events, no conversations, no mutual aid, no governance, no sense of community. A shared doc can track decisions but can’t facilitate them. Groups that try to coordinate entirely through docs end up with organized information and disorganized people.',
    hylo: [
      { t: 'A living community, not a filing cabinet.', d: 'Hylo is where your people actually interact — conversations, events, requests, offers, proposals, projects. The human coordination layer that docs can’t provide.' },
      { t: 'Documents still have a home.',    d: 'Hylo supports resource posts where you can share files, links, and reference materials. Use Hylo for coordination and keep Notion or Google Docs for the documents that need them.' },
      { t: 'Governance is participatory, not just documented.', d: 'Instead of writing governance rules in a doc and hoping people follow them, Hylo’s proposals, agreements, and roles make governance a living practice.' },
    ],
    migration: 'You probably don’t need to fully leave Notion or Google Docs — and shouldn’t. Use Hylo as the community coordination layer and link to documents where needed. The shift is: your group’s home moves from a collection of docs to a living social space, with docs attached where they’re useful.',
  },
];
